// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.0
// source: ppmessage.proto

package ppmessage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InstMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     uint64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Activepower   float64 `protobuf:"fixed64,2,opt,name=activepower,proto3" json:"activepower,omitempty"`
	Reactivepower float64 `protobuf:"fixed64,3,opt,name=reactivepower,proto3" json:"reactivepower,omitempty"`
	Current       float64 `protobuf:"fixed64,4,opt,name=current,proto3" json:"current,omitempty"`
	Voltage       float64 `protobuf:"fixed64,5,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Phaseid       uint32  `protobuf:"varint,6,opt,name=phaseid,proto3" json:"phaseid,omitempty"`
}

func (x *InstMessage) Reset() {
	*x = InstMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ppmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstMessage) ProtoMessage() {}

func (x *InstMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ppmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstMessage.ProtoReflect.Descriptor instead.
func (*InstMessage) Descriptor() ([]byte, []int) {
	return file_ppmessage_proto_rawDescGZIP(), []int{0}
}

func (x *InstMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InstMessage) GetActivepower() float64 {
	if x != nil {
		return x.Activepower
	}
	return 0
}

func (x *InstMessage) GetReactivepower() float64 {
	if x != nil {
		return x.Reactivepower
	}
	return 0
}

func (x *InstMessage) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *InstMessage) GetVoltage() float64 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *InstMessage) GetPhaseid() uint32 {
	if x != nil {
		return x.Phaseid
	}
	return 0
}

var File_ppmessage_proto protoreflect.FileDescriptor

var file_ppmessage_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x70, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x70, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xc1, 0x01, 0x0a,
	0x0b, 0x49, 0x6e, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x76,
	0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x68, 0x61, 0x73, 0x65, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x68, 0x61, 0x73, 0x65, 0x69, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ppmessage_proto_rawDescOnce sync.Once
	file_ppmessage_proto_rawDescData = file_ppmessage_proto_rawDesc
)

func file_ppmessage_proto_rawDescGZIP() []byte {
	file_ppmessage_proto_rawDescOnce.Do(func() {
		file_ppmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ppmessage_proto_rawDescData)
	})
	return file_ppmessage_proto_rawDescData
}

var file_ppmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ppmessage_proto_goTypes = []interface{}{
	(*InstMessage)(nil), // 0: ppmessage.InstMessage
}
var file_ppmessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ppmessage_proto_init() }
func file_ppmessage_proto_init() {
	if File_ppmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ppmessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ppmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ppmessage_proto_goTypes,
		DependencyIndexes: file_ppmessage_proto_depIdxs,
		MessageInfos:      file_ppmessage_proto_msgTypes,
	}.Build()
	File_ppmessage_proto = out.File
	file_ppmessage_proto_rawDesc = nil
	file_ppmessage_proto_goTypes = nil
	file_ppmessage_proto_depIdxs = nil
}
